### ISSUE TITLE
auditorium: command not found

### ISSUE THREAD

**Issue by pybokeh** [apiad/auditorium#30]
Hi, I am using version 0.6.1 and I can't and my OS (Ubuntu 18.04) can't seem to find the auditorium command. Did a pip install auditorium and then tried: auditorium demo  I looked at my installation directories and can't seem to find auditorium anywhere.

**Comment by pybokeh** [comment]
Downgraded to version 0.6.0, auditorium command was recognized, but then I got an error when attempting to run the demo via: auditorium demo:

```
(presentations) pybokeh@lemur-laptop:~/envs/presentations$ auditorium demo
[2019-12-18 19:55:40 -0500] [13984] [INFO] Goin' Fast @ http://localhost:6789
[2019-12-18 19:55:40 -0500] [13984] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 118, in run
    loop.create_task(task(self))
TypeError: launch_server() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/server.py", line 632, in trigger_events
    result = event(loop)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 120, in run
    loop.create_task(task())
  File "uvloop/loop.pyx", line 1396, in uvloop.loop.Loop.create_task
TypeError: a coroutine was expected, got None
Traceback (most recent call last):
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 118, in run
    loop.create_task(task(self))
TypeError: launch_server() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pybokeh/envs/presentations/bin/auditorium", line 8, in <module>
    sys.exit(main())
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/auditorium/__main__.py", line 34, in main
    fire.Fire(Auditorium, name='auditorium')
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/auditorium/__main__.py", line 23, in demo
    show.run(host, port, debug=debug, launch=launch)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/auditorium/show.py", line 63, in run
    self.app.run(host=host, port=port, *args, **kwargs)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/server.py", line 632, in trigger_events
    result = event(loop)
  File "/home/pybokeh/envs/presentations/lib/python3.7/site-packages/sanic/app.py", line 120, in run
    loop.create_task(task())
  File "uvloop/loop.pyx", line 1396, in uvloop.loop.Loop.create_task
TypeError: a coroutine was expected, got None
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

Created a file.py file and added example code, then executed via: auditorium run file.py, got the same error as above.

Perhaps I should downgrade to version 0.5.1.

**Comment by apiad** [comment]
Unfortunately version 0.6.* is totally broken at this point. I changed to Poetry as package manager and apparently completely broke the dependencies. Auditorium doesn't work on Python 3.8 (yet) because coroutines work differently, so it shouldn't be installed on Python 3.8, but my Poetry configuration allows for that. At this point I think nothing over 0.5.* is working.

Thanks for heads up :+1:

**Comment by apiad** [comment]
@pybokeh It is fixed now on version 0.6.3. Sorry but I had to restrict it to Python 3.6 for now. I'm working on the portability issue. Hope it works for you! :smile:

**Comment by pybokeh** [comment]
@apiad FYI, I was using Python 3.7, not 3.8.  I will try with 3.6.  Thanks!

**Comment by apiad** [comment]
Thanks, I've added #34 specifically for that purpose. I'm planning on using `tox` but have no experience with it, so it'll take me some time.
